<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Johan Classon</Authors>
        <Company>Classon Consulting AB</Company>
        <PackageDescription>A TokenCredential decorator with caching behavior.</PackageDescription>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/CABGroupAB/Classon.Identity</RepositoryUrl>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Core" Version="1.61.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
