name: Build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # GitHub suppresses push-triggered workflow runs resulting from GITHUB_TOKEN actions, 
    # such as from .github/dependabot.yml.
    - cron: '0 20 * * 0'

defaults:
  run:
    shell: pwsh

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          ./scripts/build.ps1 -Publish:($env:EVENT_NAME -ne 'pull_request')
